### ISSUE TITLE
Don't have vinh bui brand and phong dang branch

### ISSUE THREAD

**Issue by vnhdev** [GnourtNaux/notes-web#1]
I can't find vinh bui branch and phong dang branch in here. Master brand isn't necessary here so add vinh bui branch and phong dang branch in and let it go.

**Comment by GnourtNaux** [comment]
5$ per day for each branch you want. But first, you have to pay for the meal that you owe me. Many thanks <3

**Comment by phongdang707** [comment]
I'm waiting for Phở @vnhdev

**Comment by GnourtNaux** [comment]
![image](https://user-images.githubusercontent.com/126371211/221756758-e295cc33-05ee-43a9-95b2-1aac802b9fc6.png)
As you can see, there's no Vinhbui's brand here

**Comment by hi991016** [comment]
$2000 is coming
